/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuAplicacionServidor.java
 *
 * Created on 27/05/2009, 11:28:10 PM
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.DefaultDesktopManager;
import javax.swing.DesktopManager;

/**
 *
 * @author zAxA
 */
public class MenuAplicacionServidor extends javax.swing.JFrame {

    private DialogoRealizarConfiguracionSimulador dlgConfigurarSimulador;
    private DialogoRealizarConfiguracionUsuario dlgConfigurarUsuario;
    private DialogoAgregarProceso dlgAgregarProceso;

    /** Creates new form MenuAplicacionServidor */
    public MenuAplicacionServidor() {

        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension tamano = toolkit.getScreenSize();
        this.setPreferredSize(new Dimension(tamano.width, tamano.height - 30));
        initComponents();

        DesktopManager a = new DefaultDesktopManager();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProceso = new javax.swing.JTable();
        jmbBarra = new javax.swing.JMenuBar();
        jmConfigurar = new javax.swing.JMenu();
        jmiConfigurarSimulador = new javax.swing.JMenuItem();
        jmiConfigurarUsuarios = new javax.swing.JMenuItem();
        jmSimulador = new javax.swing.JMenu();
        jmiAgregarProceso = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador de Sistema Operativo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        tbProceso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbProceso);

        jmConfigurar.setText("Configuración");

        jmiConfigurarSimulador.setText("Configurar Simulador");
        jmiConfigurarSimulador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConfigurarSimuladorActionPerformed(evt);
            }
        });
        jmConfigurar.add(jmiConfigurarSimulador);

        jmiConfigurarUsuarios.setText("Configurar Usuarios");
        jmiConfigurarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConfigurarUsuariosActionPerformed(evt);
            }
        });
        jmConfigurar.add(jmiConfigurarUsuarios);

        jmbBarra.add(jmConfigurar);

        jmSimulador.setText("Simulador");

        jmiAgregarProceso.setText("Agregar Proceso");
        jmiAgregarProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarProcesoActionPerformed(evt);
            }
        });
        jmSimulador.add(jmiAgregarProceso);

        jMenuItem1.setText("Ver Procesos");
        jmSimulador.add(jMenuItem1);

        jmbBarra.add(jmSimulador);

        setJMenuBar(jmbBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(468, 468, 468)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiConfigurarSimuladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConfigurarSimuladorActionPerformed
        // TODO add your handling code here:
        if (dlgConfigurarSimulador != null) {
            dlgConfigurarSimulador = new DialogoRealizarConfiguracionSimulador(this, true);
            dlgConfigurarSimulador.setLocationRelativeTo(this);
        }
        dlgConfigurarSimulador.setVisible(true);
}//GEN-LAST:event_jmiConfigurarSimuladorActionPerformed

    private void jmiConfigurarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConfigurarUsuariosActionPerformed
        // TODO add your handling code here:
        if (dlgConfigurarUsuario != null) {
            dlgConfigurarUsuario = new DialogoRealizarConfiguracionUsuario(this, true);
            dlgConfigurarUsuario.setLocationRelativeTo(this);
        }
        dlgConfigurarUsuario.setVisible(true);
}//GEN-LAST:event_jmiConfigurarUsuariosActionPerformed

    private void jmiAgregarProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarProcesoActionPerformed
        // TODO add your handling code here:

        dlgAgregarProceso = new DialogoAgregarProceso(this, true);
        dlgAgregarProceso.setVisible(true);

}//GEN-LAST:event_jmiAgregarProcesoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu jmConfigurar;
    private javax.swing.JMenu jmSimulador;
    private javax.swing.JMenuBar jmbBarra;
    private javax.swing.JMenuItem jmiAgregarProceso;
    private javax.swing.JMenuItem jmiConfigurarSimulador;
    private javax.swing.JMenuItem jmiConfigurarUsuarios;
    private javax.swing.JTable tbProceso;
    // End of variables declaration//GEN-END:variables
}
